package org.iocaste.shell.common;

public enum Const {
    NONE, STATUS, ERROR, WARNING, BUTTON, FORM, FORM_ITEM, LINK,
    MENU, MENU_ITEM, STANDARD_CONTAINER, TABLE, TABLE_ITEM, TEXT,
    TEXT_FIELD, PARAMETER, PASSWORD
}
