package org.iocaste.shell.common;

public enum Const {
    NONE, STATUS, ERROR, WARNING, BUTTON, DATA_FORM, DATA_FORM_ITEM,
    FILE_ENTRY, LINK, MENU, MENU_ITEM, STANDARD_CONTAINER, TABLE, TABLE_ITEM,
    TEXT, TEXT_FIELD, PARAMETER, PASSWORD
}
