package org.iocaste.shell.common;

public enum Const {
    NONE, STATUS, ERROR, WARNING, BUTTON, CHECKBOX, DATA_FORM, DATA_ITEM,
    DATA_VIEW, DETAILED, EXPAND_BAR, FILE_ENTRY, FORM, FRAME, HTML_TAG, LINK,
    LIST, LIST_BOX, MENU, MENU_ITEM, NODE_LIST, PAGE_CONTROL, PARAMETER,
    PASSWORD, RADIO_BUTTON, SEARCH_HELP, SINGLE, STANDARD_CONTAINER,
    TABBED_PANE, TABLE, TEXT, TEXT_FIELD
}
