package org.iocaste.shell.common;

/**
 * Define constantes para elementos e status de mensagens.
 * 
 * @author francisco.prates
 *
 */
public enum Const {
    NONE, STATUS, ERROR, WARNING, BUTTON, CHECKBOX, DATA_FORM, DATA_ITEM,
    DATA_VIEW, DETAILED, EXPAND_BAR, FILE_ENTRY, FORM, FRAME, HTML_TAG, LINK,
    LIST_BOX, NODE_LIST, PAGE_CONTROL, PARAMETER, PASSWORD, RADIO_BUTTON,
    RANGE_FIELD, SEARCH_HELP, SINGLE, STANDARD_CONTAINER, TABBED_PANE, TABLE,
    TEXT, TEXT_AREA, TEXT_FIELD, VIRTUAL, CANVAS, CUSTOM_CONTAINER,
    TABLE_ITEM
}
